
newIssueWelcomeComment: |
  Thanks for digging in and opening an Issue here. Resuminator is awesome because of people like. 
  
  ![INVESTIGATE](https://media.giphy.com/media/y9NdYQ4ddDq4WbtkGc/giphy.gif)
  
  Make sure to follow Issue Template & Contributing Guidelines! 


newPRWelcomeComment: |
  Thanks for going the extra mile and opening this PR! 
  
  Make sure to complete PR Template and read our contributing guidelines. 
  
  ![Thanks](https://media.giphy.com/media/8Iv5lqKwKsZ2g/giphy.gif)


firstPRMergeComment: |
  Congrats on merging your first pull request! We here at Resuminator are proud of you! 
  
  ![Congrats](https://media.giphy.com/media/xT0xezQGU5xCDJuCPe/giphy.gif)



