
newIssueWelcomeComment: |
  Thanks for digging in and opening an Issue here. Resuminator is awesome because of people like you. 
  
  
  
  Make sure to follow Issue Template & Contributing Guidelines! 


newPRWelcomeComment: |
  Thanks for going the extra mile and opening this PR! 
  
  Make sure to complete PR Template and read our contributing guidelines. 
  


firstPRMergeComment: |
  Congrats on merging your first pull request! We here at Resuminator are proud of you! 
  
  



